# Shared Folders
folders:
  source: src # Asset, JavaScript, Service Worker, and Sass source folder
  pages: pages # HTML source, relative to project root
  templates: templates # HTML templates, relative to project root
  includes: _components # HTML includes, relative to template directory
  layouts: _layouts # HTML layouts, relative to template directory
  output: public # Output folder for all files

# JavaScript Input/Output Config
#   output: input
#     output - Output file (no extension)
#     input - Input file (with extension) from folders.source
javascript:
  esm:
    js/main: js/main.js
    js/worklets/circles: js/worklets/circles.js
  iife:
    js/search-worker.js: js/search-worker
  chunkFileNames: '[name].js'

# Service Worker Config
serviceWorker:
  src: sw.js
  dest: sw.js
  precache: # Glob patterns to precache when Service Worker is installed
    - css/**/*.css
    - js/**/*.js
    - _components/**/*.txt
    - images/icons/sprite.svg
    - en/index.html
    - index.html
    - 404.html
    - '**/404/index.html'
    - offline/**/index.html

# Sass Config
sass:
  src: sass/**/*.scss
  dest: css
  lint: true
  config:
    outputStyle: compressed
    includePaths:
      - node_modules/breakpoint-sass/stylesheets
      - node_modules/sass-toolkit/stylesheets

# Static Asset Folders
assets:
  videos:
    src: videos/**/*
    dest: videos
  fonts:
    src: fonts/**/*
    dest: fonts
  manifest:
    src: manifest.json
    dest: ''

# Image optimization
images:
  resize:
    min: 250
    max: 1500
    step: 150
  gifToVideo: true
  sizes: 100vw
  lazy: true
  additional:
    - images/icons/**/*
  watch:
    src: images/**/*
    dest: images/**/*

# HTML Optimization
#   src is relative to the _output_ folder, not the pages or source folder.
optimize:
  src:
    - '**/*.html'
    - '**/*.txt'
  htmlmin:
    collapseWhitespace: true
    sortAttributes: true
    sortClassNames: true
    minifyCSS: true
    minifyJS: true

# Configure Eleventy Plugin Safe External Links
externalLinks:
  files:
    - .html
    - .txt
